# Generated by Django 3.2.10 on 2023-05-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstdb',
            old_name='Type',
            new_name='Types',
        ),
    ]
