# Generated by Django 3.2.10 on 2023-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_seconddb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seconddb',
            old_name='Size',
            new_name='Quantity',
        ),
        migrations.AddField(
            model_name='seconddb',
            name='Colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seconddb',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firstdb',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
