# Generated by Django 3.2.10 on 2023-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DecorApp', '0002_auto_20230530_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='productprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
